version: "3"
services:
  backend:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    expose:
      - 5000
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
      - ./server:/app
  frontend:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./client:/app
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - '3050:80'
    depends_on:
      - frontend
      - backend
