version: "3"
services:
  backend:
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    image: alikingravi/online-reviews-backend-dev
    expose:
      - 5000
    ports:
      - "5000:5000"
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - BACKEND_PORT=5000
      - FRONTEND_PORT=3000
      - DB_NAME=onlinereviews
      - DB_USER=onlinereviews
      - DB_PASS=onlinereviews
      - HOST=localhost
      - JWT_SECRET=secret_jwt
  frontend:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    image: alikingravi/online-reviews-frontend-dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./client:/app
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    image: alikingravi/online-reviews-nginx-dev
    ports:
      - "3050:80"
    depends_on:
      - frontend
      - backend
