"use strict";

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert("reviews", [
      // iPhone XS
      {
        userId: 3,
        productId: 1,
        title: "Solid Performer",
        reviewtext:
          "This phone came in perfect packaging, thanks to Amazon. The phone itself was bought for my wife, who loves it. The gold colour really does look very nice and you can tell the build quality is very premium. I think the face unlock is good but they should have kept the fingerprint scanner.",
        rating: 4,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 5,
        productId: 1,
        title: "No clarity on warranty",
        reviewtext:
          "Neither the microphone nor the speakers on this telephone work properly. More troublesome I don’t know how to get the warranty on it. Does it go to Apple? Nobody tells you.",
        rating: 1,
        recommend: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 6,
        productId: 1,
        title: "Excellent Product",
        reviewtext:
          "Great product like every Apple. All people what writing bad stuff need to check reference and description of the product on Apple website and then decide to buy or not to buy. I was using iPhone 6s all this time and now buy XS and I love it.",
        rating: 5,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 7,
        productId: 1,
        title: "Best phone on the market",
        reviewtext:
          "Over the last few months this phone has obliterated anything thrown at it from intensive programs to 4K live streams, augmented reality it can handle anything, it is raw power. Battery life is poor, if you are a power user you will be out of charge within 6 - 8 hours. So keep that in mind. I’ve dropped this phone on solid marble tiles and it didnt leave a scratch, they are durable, but take no risk, buy a sturdy case.",
        rating: 5,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 9,
        productId: 1,
        title: "Cannot recommend enough",
        reviewtext:
          "Arrived swiftly and perfectly packaged. Adore the phone. Cannot recommend enough!",
        rating: 5,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 10,
        productId: 1,
        title: "Do not get wet!",
        reviewtext:
          "Apple actively tout this phone as a product you can submerge in clean water up to 1m . I decided to test this out by putting the phone in a mug of tap water - IT DIED IMMEDIATELY ! Iphone have told me the phone is not waterproof and should never be immersed in water. They have hidden behind a small print clause that states if you get the phone wet , you do so at your own risk!",
        rating: 2,
        recommend: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 12,
        productId: 1,
        title: "Almost perfect",
        reviewtext:
          "Decided to switch to iPhone after a decade of android devices. I’m impressed, the phone is extremely smooth, the amoled screen is beautiful, the stainless steel makes it feel truly premium, all the apps on the store are brilliantly optimised and the camera is great. There is one issue, the battery life is atrocious. When using mobile data the battery just drops like a sack of potatoes.",
        rating: 3,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // ASUS Monitor
      {
        userId: 4,
        productId: 2,
        title: "Very crisp quality",
        reviewtext:
          "I upgraded from a 10 year old 19 inch monitor so this is outstanding. I also see some people complain about dead pixels, I have 1 dead pixel in my monitor which is quite unacceptable for a £300 monitor, although Amazon did give me a 10% refund because of this issue.",
        rating: 5,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 5,
        productId: 2,
        title: "Amazing screen",
        reviewtext:
          "The monitor is pretty good quality it does 1920x1080p at 165hz via the display port which is a good feature , it's a shame there is a black border round the screen due to the pixels not being able to stretch as its a 27in monitor with the pixles of a 24 . The picture quality is very good and after messing around with the settings can be outstanding . It can move up, down can be tileted and turned onto side it's pretty good.",
        rating: 4,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 7,
        productId: 2,
        title: "Blurry text",
        reviewtext:
          "The reason why I deducted 2 stars of it is because when viewed from a +/- 40 degrees angle in both vertical and horizontal axis simultaneously (so slightly to left/right and top/bot at same time), the font of any email, web browser, document, really just any font, even like Windows icons font, was double and blurry and it gave a tremendous eye strain. Like I use glasses and was having trouble determining whether I needed my glasses grade updated? Just an awful experience with that so I returned the monitor.",
        rating: 3,
        recommend: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 8,
        productId: 2,
        title: "Stuck after 8 months of use!",
        reviewtext:
          "In 4 months the monitor has a stuck cyan pixel. Asus refuse to refund/replace because the warranty only covers you if you have 3 or more dead/bright pixels. Their monitors with the warranty for ZBD (zero bright dark pixel) is extremely hard to seach and find. Their other warranties are hidden within downloadable pdfs and such.",
        rating: 1,
        recommend: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 9,
        productId: 2,
        title: "Fantastic Monitor!",
        reviewtext:
          "I got this monitor whilst on offer and I’m really glad I bought this. This monitor at 165ghz (tested and confirmed) is the sweet spot, FreeSync (g sync compatible works like a treat, no more worries about screen tearing.",
        rating: 5,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 11,
        productId: 2,
        title: "Terrible for reading",
        reviewtext:
          "Tried this monitor for two days now, I can't seem to be able to ajust the fonts so they don't look pixelated after hours of forum readings and playing with the settings both in Windows and on the screen itself.",
        rating: 2,
        recommend: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Audio Technica ATH-M50X
      {
        userId: 3,
        productId: 3,
        title: "Outstanging Value",
        reviewtext:
          "I was looking to replace a set of Senheiser headphones I'd had for quite some years. The headphones had really seen better days as they are my day to day set that get used on anything from a laptop, mobile phone or even my Hi-fi or Sony Hi-Res Audio Player. I own a series of Beyer Dynamic headphones that are souley for studio use. Their impedance are quite high and in order for me to get the best from them I would have to get an additional headphone amp to carry about with me.",
        rating: 5,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 8,
        productId: 3,
        title: "Crystal Clear!",
        reviewtext:
          "No disrespect to Sennheiser, as I do believe they make solid products, however once I put these Audio Technicas on, I immediately noticed a difference to my Senn. HD280 Pro headphones. Absolutely nothing is lacking, and I'm glad I went with these from recommendations.",
        rating: 5,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 10,
        productId: 3,
        title: "Awful Headphones",
        reviewtext:
          "I, like many others here, made the huge mistake of buying these headphones based on a handful of reviews by trusted Youtube creators (*facepalm). The problem being that most of these Youtube creators either Haven't really listened to any headphones of relatively decent audio quality beyond 'Beats' by Dre (which are also total garbage) or a pair of similarly overpriced brand name IEM's OR have simply been paid to promote certain products they were, more often than not, given for free.",
        rating: 1,
        recommend: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 11,
        productId: 3,
        title: "Very capable cans for tunes on the go",
        reviewtext:
          "Had these for about three weeks now, listening mainly to 320kbps tracks on Google music on a nexus 5x phone. I can totally see why people like these, the signature on these is very pleasant, sounding well with all musical genres. You can tell there's monitor heratige, but they've been slightly tuned for more modern tastes. Sound is clean, clear, confident and enjoyable, and at 32 ohms they're dead easy to drive.",
        rating: 5,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Echo Dot
      {
        userId: 3,
        productId: 4,
        title: "So much better that the last gen",
        reviewtext:
          "So being the owner of the first and second generation Echo Dot I was nervous to purchase this item as I thought that I should go for the larger Echo plus. I needn't of worried, the sound improvement between this and the older models is massive. A real hearty base and more fuller sound.",
        rating: 5,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 5,
        productId: 4,
        title: "Good smart speaker",
        reviewtext:
          "I've been picking up Echo Dots when they've been on offer over the Summer. They're good speakers, but what makes them are the accessories you can get to go with them. I have a holder that hides away all the wiring and acts as an amplifier, improving the sound (Proud Bird Wall Mount Stands) as well as a battery base - the GGMM D3 - which makes it truly portable and is great for the summer or when you want to move around the house and take the Echo Dot with you. You can see them both in my video.",
        rating: 4,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 7,
        productId: 4,
        title: "Compact but loud enough",
        reviewtext:
          "Already own the first generation Echo Plus (lives in my lounge) so I decided to buy an Echo Dot third generation for my bedroom. I didn't like the default sound from the new Dot so I went into the Alexa app and adjusted the equaliser which offers up to 6dB cut or boost - I cut bass by 2dB, boosted mids by 2dB and boosted treble by 6dB - this sounds better to me for both speech and music but I suggest you play with the equaliser to suit your needs. Volume is just fine for a small room, I've never wanted to use the maximum available.",
        rating: 4,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 9,
        productId: 4,
        title: "Beware of music prices",
        reviewtext:
          "If you intend buying an Alexa device to play music through you need to be aware that Amazon only permits you to use your £3.99 monthly subscription for ONE device. If you add another Alexa device you will not be able to play your Amazon Music with it unless you upgrade your monthly subscription to £9.99 or £15.99 if you would like your music played simoustainaly through two or more devices. Amazon doesn’t tell you this when you purchase Alexa devices, so be warned.",
        rating: 1,
        recommend: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 11,
        productId: 4,
        title: "It works",
        reviewtext:
          "Arrived on time..given as a present..she loves it..I am slightly hard of hearing so it wasn't as clear as hoped,,,but great for music and good hearing people as great music sound..I have a echo dot 2nd generation..I prefer this one for sound quality.",
        rating: 3,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 12,
        productId: 4,
        title: "Not that good",
        reviewtext:
          "Well i was sucked in with the marketing, Ive unplugged it & looking for the box it came in to sell on a local buy & sell site, i have the bigger one also, that was a present....thats set behind the tv unplugged as well, got fed up of it continually playing random things & waking up, but not responding well to songs requested.",
        rating: 2,
        recommend: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Henery Vacuum
      {
        userId: 6,
        productId: 5,
        title: "Cumbersome but certainly cleans well",
        reviewtext:
          "After many years of using upright cleaners, I've switched to Henry. Resisted it for a long time, because I've never liked pull-along cleaners, I find them awkward to use. However, having spent probably three times the price of this unit on rubbish uprights over the last few years, I decided to go for it.",
        rating: 4,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 7,
        productId: 5,
        title: "Sucks like a sucking thing!",
        reviewtext:
          "No need to spend much time assembling this chap, he will do it himself!! Within seconds he was fumbling around in the box, taking out various pieces and slotting them in here and there. With the harder to reach areas he would hand me an object and gesture as to where it went and then followed by what motion i needed to complete the task, i.e screw or push. Id give young henry five stars. He has very strong suction and a long cable. By far the best hoover ive ever used (dyson included).",
        rating: 5,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 8,
        productId: 5,
        title: "We love Henry",
        reviewtext:
          "My brother bought one of these and the way he was talking about it I thought he’d had another child!!! ‘Henry this, Henry that, Henry is amazing’ anyway, after lugging my heavy Dyson about for years I decided to wade into Henry World. People warned me against it, my mother-in-law said I’d hate a Henry, even my hubby stared at it when it came and refused to show interest.",
        rating: 5,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 9,
        productId: 5,
        title: "Did not live up to expectations",
        reviewtext:
          "Very disappointed in this product as I have used the earlier versions of this cleaner and was impressed. Cheap brittle plastic hose that pulled loose the very first time the machine was used. Altogether a cheap feel to the cleaner and materials used. Did not handle at all well.",
        rating: 1,
        recommend: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 10,
        productId: 5,
        title: "Easy to use and powerful suction too",
        reviewtext: "Can't beat a Henry! Easy to use and powerful suction too.",
        rating: 4,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 11,
        productId: 5,
        title: "I love Henry, RIP Harry",
        reviewtext:
          "After the sad death of Harry (the green vacuum) I decided to purchase his brother Henry. Harry had been with us for many years and it was a tough decision to replace him. Well what can I say Henry is fantastic. He’s a little bit smaller than Harry but boy is he powerful. He’s lightweight and has a lovely long cord which makes hoovering a breeze. I would definitely recommend him.",
        rating: 5,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Samsung tv
      {
        userId: 3,
        productId: 6,
        title: "Great TV",
        reviewtext:
          "I'd had my old TV for almost 10 years (720p 42\") so thought it was definitely time for an upgrade. The difference is incredible, the picture is so sharp, even watching older shows like friends it was really different, it took a little while to get used to it!",
        rating: 5,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 4,
        productId: 6,
        title: "Great TV as always",
        reviewtext: "It does what a TV was made to do.",
        rating: 5,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 5,
        productId: 6,
        title: "Great",
        reviewtext:
          "Its brilliant. Picture quality fantastic and easy to set up. I missed the delivery date but everything great when contacting retailer and couriers are early birds.",
        rating: 5,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 6,
        productId: 6,
        title: "Awesome TV",
        reviewtext: "Its a great TV. Highly recommended.",
        rating: 5,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 11,
        productId: 6,
        title: "Top drawer",
        reviewtext: "Bargain, its mint tbh!",
        rating: 5,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Canon DSLR
      {
        userId: 7,
        productId: 7,
        title: "Canon DSLR Camera",
        reviewtext:
          "This is Canon’s new ‘entry level,’ camera, which is ideal for a beginner. So many people rely on smartphones now, but this is a camera designed to get people away from using these and back to cameras. This cuts costs by using a plastic, rather than metal, lens mount. On the plus side, this is fairly easy to use, with well laid out controls and good battery life. It is also well priced, compared to many cameras on the market and so is obviously marketed at those who want to try using a camera again, rather than those cellphones.",
        rating: 4,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 8,
        productId: 7,
        title: "Very good and easy to use",
        reviewtext:
          "I have read in other reviews this is a good starting point so not the camera to get if already a professional but perhaps a good starting point if interested in getting into photography. That does seem like quite the commitment considering the price of this camera but it really does seem like a good bit of kit. When you hear Canon and cameras you know you are in good hands.",
        rating: 5,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 9,
        productId: 7,
        title: "Excellent camera",
        reviewtext:
          "I am not a camera person I bought this for special occasion etc and it more than fits the bill, this thing does all the picture taking for you really just point and it can automatically zoom and get the best picture brilliant.",
        rating: 3,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 10,
        productId: 7,
        title: "Shame",
        reviewtext:
          "Is this a bad camera? No it's not, but the reason you buy any DSLR is for quality photography. It shoots RAW, has aspect ratio in the menu, which is a bonus, can do a few fancy picture affects, the camera app to connect to wifi is easy once you see how it works, it might take a few tries, but once it's up and running it does work well and you can transfer pictures to Flickr and Instagram easily enough.",
        rating: 2,
        recommend: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 12,
        productId: 7,
        title: "Entry level",
        reviewtext:
          "Be careful why you buy this camera. Yes if you want to start photography, to learn using Aperture, ISO, shutter speed etc is fine but if you want something more you can’t. I bought t this camera to attend a workshop but it let me down. I couldn’t sync this camera with any flash, and not with studio flashes. Let me tell you that I borrowed another camera during the workshop.",
        rating: 3,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Samsung Galaxy Tab A
      {
        userId: 3,
        productId: 8,
        title: "Average",
        reviewtext:
          "Bought this for my son. Notices that the screen edges shows the led lights in an uneven way... light and dark spots on the screen side. See on the picture. This is a black screen displayed on the tablet. You can spot the left side is showing an un even lighting less... this reminded me with a cheap Chinese Tablets.",
        rating: 2,
        recommend: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 4,
        productId: 8,
        title: "Fantastic",
        reviewtext:
          "Brilliant tablet, suits all my needs. Screen bright, crisp and clear, android Pie out the box is superb. Very happy, feel like it's worth double the asking price. Just waiting for an official case from Samsung. My only small gripe is the speaker position, they sound fantastic for a tablet, however both on one side when in landscape watching movies, should have had one each side for better use of the Dolby Atmos and proper stereo sound.",
        rating: 5,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 5,
        productId: 8,
        title: "Not as advertised",
        reviewtext:
          "Bought this as a possible replacement for an older model, a Samsung Tablet 3 to be exact. The size of the model itself is 11 inches from top right to bottom left corners of the model, and the screen despite being sold as a 10.1 inch is instead 9.8 inches. Even though this 3 inch may seem small, it makes a world of difference for someone with bad eyesight.",
        rating: 1,
        recommend: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 7,
        productId: 8,
        title: "Buy it now",
        reviewtext:
          "I love it size is perfect i got the keyboard case to go with it and its just like a smaller laptop perfect for everyday use defo recommend.",
        rating: 4,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 8,
        productId: 8,
        title: "Great Value Tablet!",
        reviewtext:
          "Worthy replacement for my old Galaxy Tab S. It's sound and picture resolution is very good and it has an Octo core processor so it's great with multiple apps together without slowdown.",
        rating: 5,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 9,
        productId: 8,
        title: "A Quality Tablet!",
        reviewtext:
          "This is still new to me and I have had some issues with connecting to wi-fi networks in Italy except in the large cities. I have also had some problems with the camera sticking and not taking the photographs every time. The manual has not been helpful for the camera and of course I couldn't access it on-line when I could not connect to a wifi.",
        rating: 3,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 10,
        productId: 8,
        title: "Touch screen is ok",
        reviewtext:
          "The experience of using this tablet is average due to that many times I have to tap 2 to 5 times for a click to happen. The screen is quite unresponsive. I don't know if it is a software or hardware issue but it is what it is.",
        rating: 2,
        recommend: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 11,
        productId: 8,
        title: "Very good value for money",
        reviewtext:
          "I've had a samsung s2 tablet for 4 years and my son smashed his old lenovo tablet on holiday and needed another, I thought I couldn't go wrong with Samsung. The quality of this item is brilliant - screen is fine and build quality belies the price - performance for gaming and youtube seems fine as well. Very good value - I'll be replacing my s2 when it dies with one of these.",
        rating: 5,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Seagate HD
      {
        userId: 8,
        productId: 9,
        title: "Broke after 3 months",
        reviewtext:
          "I have had this hard drive since May. I trusted seagate and I made sure I always ejected the hard drive after using it. Recently, it broke for no reason and it won’t display on my computer and all my files are gone. The hard drive won’t even show up in disk management. I’m very upset as I had important videos and photos on there (around 2tb). Is they’re any chance I could be refunded as the hard drive is broken.",
        rating: 1,
        recommend: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 9,
        productId: 9,
        title: "Robbed!",
        reviewtext:
          "I bought this for storing a back up of my work (years of teaching lessons from year 7 to 13. Used it 4 times and then it stopped working. Seagate offered to replace it through guarantee but I'd have to pay £600+ to get my data restored.",
        rating: 1,
        recommend: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 10,
        productId: 9,
        title: "Failed after 1 month",
        reviewtext:
          "Worked Fine For just over a month, could be a little noisy at times (vibration from HDD) Then failed without warning not recognised on either PC or MAC and HDD just spins up, ticks twice then spins down. Very disappointed as this was bought following good reviews and I was relying on it for continuous backup.",
        rating: 1,
        recommend: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 11,
        productId: 9,
        title: "Works well",
        reviewtext:
          "Plugged USB connection straight into my Samsung Q7 4K TV to use for recording and playback of programs. Needs no power of its own and small and neat. I've had the TV and storage device for a couple of months and used for record/play back of HD programs many times. I did lose connection between the TV and Device once but restarting the TV solved this. I suspect this was the fault of the TV rather than the device.",
        rating: 5,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 12,
        productId: 9,
        title: "Good if it works",
        reviewtext:
          "Bought for my Xbox one. After using it for about a year it worked really well my son bought the same one and it’s still working. However mine has stopped working it stops the controller from working and then stops being recognised in any of the ports and fails to load any games. I thought it was my old Xbox one that was on its way out so bought a brand new 1s.",
        rating: 2,
        recommend: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // LG Home surround sound
      {
        userId: 4,
        productId: 10,
        title: "Great sound but connection issues",
        reviewtext:
          "Sound quality is EPIC! Image from the BluRay player is amazing, but the ARC function from the TV is hard to set up. Sometimes doesn’t sense when other sources are being used, have to turn everything off and on again. I’m going to check out YouTube, call Customer Services, and update this review ASAP. Possibly works brilliant with a LG TV, (next purchase), as this has direct connectivity. However, everything drops when I wanna change to playing on a games device or through Sky box, plus, there is an App in the premium section for Amazon, but when you refresh the software this disappears.",
        rating: 4,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 5,
        productId: 10,
        title: "Mediocre sound qaulity",
        reviewtext:
          "I really should have checked the DSP sound support. While this Surround sound system supports decoding of multiple Dolby etc audio formats there is a reason it makes no claims in regards to it's DSP sound reproduction.",
        rating: 3,
        recommend: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 6,
        productId: 10,
        title: "Sound is wall shattering",
        reviewtext:
          "Very well packaged and was easy to assemble just a few screws and colour coded wires you can't go wrong, connect to my LG TV and the sound is clear, room filling and fully adjustable to your liking. The centre and bass speakers pump out the normal action and voice then the front and rear speakers engulf you in total surround sound it is amazing. Was not happy with the default settings it came with, lets face it who is? Adjusted the speaker levels, EQ to my liking and never going back to watching even normal TV without these babies powered on.",
        rating: 5,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 7,
        productId: 10,
        title: "Great system",
        reviewtext:
          "I got this from the warehouse deals so I got it for a great price. The only thing different was the box was slightly damaged, the speakers and blueray player are perfect. I bought this for my sim racing rig so they aren't used for movies etc. The sound is really good, the bass is nice and really makes running over kerbs etc sound great.",
        rating: 5,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 8,
        productId: 10,
        title: "Ok-ish",
        reviewtext:
          "I purchased as I thought it was time for a upgrade from my 800wt LG 5.1 system to this 1000wt -I guess I expected too much from this system - my old model was a 2011 and this a 2018 I thought sound quality would of been greatly improved..... it sounded nearly the same maybe voices a little more crisp but bass was worse..... I have now returned and spending a lot more on something that should melt my face off.",
        rating: 3,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 9,
        productId: 10,
        title: "Beware!",
        reviewtext:
          "Turns on during the night (in turn turns the TV on as well) and then won't turn off (Have to unplug). Contacted Amazon who passed me onto LG direct. 4 weeks later still waiting for something to happen. Might get a replacement for Xmas if I'm lucky. Useless. Lesson is if you buy cheap crap you get crap performance and service.",
        rating: 1,
        recommend: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Wansview security camera
      {
        userId: 3,
        productId: 11,
        title: "Does exactly whats expected",
        reviewtext:
          "Firstly, Wansview offered me the opportunity to review this W4 camera, on the back of my purchase of two other cameras in their range(K5). It has NO impact on this review, whatsoever. I can assure you, if I hadn't been impressed with it, I would not have screwed it to my house (see photos)! Right...that's that out the way.",
        rating: 5,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 4,
        productId: 11,
        title: "Excellent Product",
        reviewtext:
          "Excellent product, a must buy for anyone considering a little more home security. After purchasing 2 x indoor cameras i decided to buy an outdoor camera to see if it had the same quality as the others, I WASN'T disappointed! It was delivered by next day deliver and comes with all you need to install straight away (see picture). It is extremely easy to install and set-up, the picture quality is amazing for the size of the camera (see picture).",
        rating: 5,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 6,
        productId: 11,
        title: "A must buy",
        reviewtext:
          "What can I say, what a fantastic bit of kit! We got ours as we were wanting some additional security on our house so we bought these after reading all the reviews from the last year we took the plunge, so glad we did, the cameras were easy to install and set up (about an hour all in that's drilling the hole from the inside out and getting them secure and set up) the app is so easy to use, you can add someone to your household so now, me and my husband can view the cameras on each phone (great when waiting for a delivery and not wanting to set the dogs off to then wake our child) the motion sensor is sensitive.",
        rating: 4,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 7,
        productId: 11,
        title: "Good quality",
        reviewtext:
          "Bought this camera to catch next doors cat on my VW camper which kept leaving dirty paw prints all over it lol. Works very well sending me a notification of detected motion giving me the chance to sneak up on it and squirt it with water, only down side was the sensativity at night as kept detecting small insects/particles via the night vision, one email to wansview explaining my problem and within 2 days they'd updated the firmware sensativity of the camera, so far this seems to have improved it.",
        rating: 4,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 9,
        productId: 11,
        title: "Absolutely crap",
        reviewtext:
          "Absolutely crap. I don't know why I bother with these crap Chinese products. The first one never arrived. This one arrived, but wouldn't set up (you have to get an email to validate installation, but you have to be validated to complain that the email wasn't sent). Will settle for something produced closer to home even if it costs more.",
        rating: 1,
        recommend: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 10,
        productId: 11,
        title: "Great product",
        reviewtext:
          "I have found this camera to be very good quality, easy clear instructions to set up- customer service are 5* they actually emailed me to check how my product was and gave me helpful tips.",
        rating: 3,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 12,
        productId: 11,
        title: "Great night vision",
        reviewtext:
          "Great camera for the home. I used a 5.5mm x 2.1mm DC extension cord. The cable supplied was around 8ft. I screwed it onto my soffit. Popped the wires through a 25mm hole (which the camera mount covered), went into the loft, pulled the wire through into the loft space and attached my 10m extension and ran it to a socket I have installed in the loft (use it for Christmas lights, camera etc). Easy to install.",
        rating: 5,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Apple watch
      {
        userId: 5,
        productId: 12,
        title: "Dont think, just buy!",
        reviewtext:
          "This is my first Apple Watch device and have to say, blew my mind away. Beautiful peace of technology that makes you think of all the great things that have come with the age of technology.",
        rating: 5,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 7,
        productId: 12,
        title: "Battery life is average",
        reviewtext:
          "Battery life is maximum of 1.5 day. If you wear it all-day , You can't track your sleep. You have to charge it again before using.",
        rating: 3,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 8,
        productId: 12,
        title: "Glad I waited for this",
        reviewtext:
          "Looks beautiful, love how the screen stays awake but it does kill the battery. You need to charge overnight, every night. I’ve now purchased a charging dock to go with. You can voice note back, answer calls, quick replies if you’re in the shower and can’t answer.",
        rating: 5,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 10,
        productId: 12,
        title: "Not worth the hype",
        reviewtext:
          "Watch was fairly easy to set up- just hold it next to your phone. However, I instantly noticed that watch was buggy and slow to respond. Also the always on feature wasn’t working. This is a big selling point for the series 5 so to not have it working was a big let down.",
        rating: 2,
        recommend: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 11,
        productId: 12,
        title: "Great for health monitoring",
        reviewtext:
          "Love the new 5 it is excellent especially for your heart monitoring.. expensive so buy the aluminium one and save some money it’s still the same inside.",
        rating: 4,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 12,
        productId: 12,
        title: "Fastest smart watch!",
        reviewtext:
          "Extremely impressed with this smart watch. Mainly wanted something which could track my heart rate but ECG function (Yes, ECG) attracted me the most. This watch superb for someone who wants their heart rate to be tracked regularly. Has a lot of in app functions. This watch has an always on display option with great analog clock interface. Battery is just superb, did my first charge after over a week of extensive use.",
        rating: 5,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Phone stand
      {
        userId: 3,
        productId: 13,
        title: "Useful!",
        reviewtext:
          "Nice but I also own the other lamicall stand which is made from full metal and i'd definitely recommend that one over this one.",
        rating: 4,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 4,
        productId: 13,
        title: "Quality",
        reviewtext: "A very good product!",
        rating: 5,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 5,
        productId: 13,
        title: "Excellent product",
        reviewtext:
          "I am very pleased with this product. It is very well made and is very sturdy. It does as described online. You can angle the stand, use it for the phone to be landscape or portrait and you can adjust the height of the phone placement on the stand.",
        rating: 5,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 6,
        productId: 13,
        title: "Clever design and looks great",
        reviewtext:
          "This is a very well designed and well made product, the finish of it is excellent. Although it's plastic, it doesn't look at all plasticy, in fact it looks quite plush. It's nicely adjustable for phone angle and height and is extremely useful if you want to use it as I do hands free on a desk.",
        rating: 4,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 7,
        productId: 13,
        title: "Really good product",
        reviewtext:
          "Really good product, exactly as described, I did have to modify the product due to my phones ear jack position but it was easy to do, the dimensions of the product really helped. In current times I am using the phone for video calls and it has enabled me to keep a stable phone with a good image.",
        rating: 3,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 9,
        productId: 13,
        title: "Poorly made",
        reviewtext:
          "It's flimsy and makes noise with evey tap!! Poorly Made. Not worth the money!!",
        rating: 2,
        recommend: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 10,
        productId: 13,
        title: "Very handy",
        reviewtext:
          "I use it along side my work laptop, it’s so much easier to see and use my iPhone on this stand. I also use it in the kitchen when I’m looking at Recipes on my iPhone. It folds flat to go in my bag. It’s brilliant. I highly recommend it. In fact I’m going to order another one for my partner because he likes it too.",
        rating: 5,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Ring door bell
      {
        userId: 5,
        productId: 14,
        title: "Takes too long to ring on phone",
        reviewtext:
          "Takes too long to come onto phone the person has gone by the time the picture has come on and the bell does not always work ,very dissapointed.",
        rating: 1,
        recommend: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 6,
        productId: 14,
        title: "Brilliant",
        reviewtext:
          "I have been waiting for this product for quite a while. Unfortunately, the camera has a minimum thickness a door must be before it will allow the locking screw to tighten the front and back to the door. Here in the UK, I have a thin PVC door which does not allow the front and back to tighten as the door needed to be another 10mms thicker.",
        rating: 3,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 7,
        productId: 14,
        title: "Very handy",
        reviewtext:
          "I use it along side my work laptop, it’s so much easier to see and use my iPhone on this stand. I also use it in the kitchen when I’m looking at Recipes on my iPhone. It folds flat to go in my bag. It’s brilliant. I highly recommend it. In fact I’m going to order another one for my partner because he likes it too.",
        rating: 5,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 8,
        productId: 14,
        title: "Very easy to install",
        reviewtext:
          "I had seen that Ring were bringing out a door view one and was pleased when it became available on Amazon. My main reason for wanting this version is so the batter is on the inside, and it requires not drilling at all.",
        rating: 5,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 9,
        productId: 14,
        title: "Horrendous customer service",
        reviewtext:
          "The second one came, I set it all up fine, then the problems started, when someone would press the bell, it froze. Had to reset it then after finally getting it back on I realised that when you tried to look at live view it was just black, no video at all.",
        rating: 2,
        recommend: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 10,
        productId: 14,
        title: "Great",
        reviewtext:
          "I have been waiting for this product for quite a while. Unfortunately, the camera has a minimum thickness a door must be before it will allow the locking screw to tighten the front and back to the door. Here in the UK, I have a thin PVC door which does not allow the front and back to tighten as the door needed to be another 10mms thicker. Thankfully I was able to design a spacer to allow fitment.",
        rating: 3,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 11,
        productId: 14,
        title: "Nice addition",
        reviewtext:
          "This is effectively a Ring Doorbell as we know it but requires no drilling or screwing as it replaces your existing peephole. Installation is a breeze, I had it up an running in a few minutes and it comes with the tool you need to remove your existing peephole. Once installed set it up via the easy to follow app and you're good to go.",
        rating: 4,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      // Solar power bank
      {
        userId: 3,
        productId: 15,
        title: "Powerful",
        reviewtext:
          "This solar charger works fast to recharge itself in sunlight with the added option to power it up via the mains. It's ideal for camping and travelling and a must have if going off grid. I use it for this one all the time on my travels. Now I can be certain that my phone will always stay powered on and people can contact me.",
        rating: 4,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 4,
        productId: 15,
        title: "Highly recommended",
        reviewtext:
          "I Brought this power bank the other day and i am super happy with it. Firstly the power bank is fairly light but seems to be made with quality in mind as its very high quality and has a stylish design. The power bank has two charging ports which i really like as it means i can charge multiple devices at once. Also the battery capacity is outstanding as it seems to charge my Samsung s10 plus multiple times before needing to be re charged.",
        rating: 5,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 5,
        productId: 15,
        title: "Good capacity",
        reviewtext:
          "A power charger with a beauty of not having a electrical plug..just some sunshine. I managed to charge two phone fully with power bank since it has 25% left. Just put on a window seal and starting charging for the light. It will perfect on holiday besides the desk chair.",
        rating: 5,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 6,
        productId: 15,
        title: "Bad",
        reviewtext:
          "it is blow up when i recharge it and i had made a complain to the amazon.",
        rating: 1,
        recommend: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 7,
        productId: 15,
        title: "Just alright",
        reviewtext: "Stop working after 1 week",
        rating: 2,
        recommend: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 8,
        productId: 15,
        title: "Lasted 1 week",
        reviewtext:
          "Solid power pack, well built and like the on board solar charger. When first charged it up it took much longer than expected, I can only assume it was totally empty on delivery. Once charged it had enough juice to charge up my Iphone twice and an Ipad. Left on a window sill during the day you can see the light flashing indicating its being charged by the sun.",
        rating: 2,
        recommend: false,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 10,
        productId: 15,
        title: "Quick recharge",
        reviewtext:
          "It's a chunky sized thing. Not as chunky considered the charging capacity. However if it had been a uniform 12v with the highest amps possible. Instead of the 12v 1amp or 12v 2.1 amp. Options available. This option would be great for a couple or maybe a tab and a phone. Apart from that. It's perfect for my emergency / away from power sources for a few days needs.",
        rating: 5,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        userId: 12,
        productId: 15,
        title: "Holds a lot of power!",
        reviewtext:
          "Love this power bank. Not only does it hold a ton of power and can charge around 7 full charges of my iPhone XR but I can have it solar recharging as i do! I’ve bought a solar power bank before but this one is a lot sleeker lighter but with no loss of power. It’s light but durable and quality made. This powerbank also charges up faster too and you get more of a Solar recharge with this.",
        rating: 5,
        recommend: true,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ]);
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("reviews", null, {});
  },
};
